e1:
	rm -rf exercise01/output || true
	python3 exercise01/solution.py lenna.png 100 100
	python3 exercise01/solution.py lenna.png 100 200
	python3 exercise01/solution.py lenna.png 200 100
	python3 exercise01/solution.py lenna.png 150 250
e2:
	rm -rf exercise01/output || true
	python3 exercise02/solution.py 100 100 10 10
	python3 exercise02/solution.py 100 200 2 2
	python3 exercise02/solution.py 200 100 1 1
	python3 exercise02/solution.py 150 250 10 10
e3:
	python3 exercise03/solution.py
e4:
	python3 exercise04/solution.py lenna.png
e5:
	python3 exercise05/solution.py
e6:
	python3 exercise06/solution.py
