do_zip:
	zip -r luis-antonio-gutierrez-guanilo-graded-practise-3.zip exercise01 exercise02 exercise03 exercise04 exercise05 exercise06 exercise07 exercise08 exercise09 exercise10 exercise11 exercise12 exercise13 exercise14 exercise15
list_zip:
	unzip -l jeremy-jeffrey-matos-cangalaya-graded-practise-3.zip
remove_zip:
	rm jeremy-jeffrey-matos-cangalaya-graded-practise-3.zip